require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LinkTagsController do

  # This should return the minimal set of attributes required to create a valid
  # LinkTag. As you add validations to LinkTag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "link_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LinkTagsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all link_tags as @link_tags" do
      link_tag = LinkTag.create! valid_attributes
      get :index, {}, valid_session
      assigns(:link_tags).should eq([link_tag])
    end
  end

  describe "GET show" do
    it "assigns the requested link_tag as @link_tag" do
      link_tag = LinkTag.create! valid_attributes
      get :show, {:id => link_tag.to_param}, valid_session
      assigns(:link_tag).should eq(link_tag)
    end
  end

  describe "GET new" do
    it "assigns a new link_tag as @link_tag" do
      get :new, {}, valid_session
      assigns(:link_tag).should be_a_new(LinkTag)
    end
  end

  describe "GET edit" do
    it "assigns the requested link_tag as @link_tag" do
      link_tag = LinkTag.create! valid_attributes
      get :edit, {:id => link_tag.to_param}, valid_session
      assigns(:link_tag).should eq(link_tag)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LinkTag" do
        expect {
          post :create, {:link_tag => valid_attributes}, valid_session
        }.to change(LinkTag, :count).by(1)
      end

      it "assigns a newly created link_tag as @link_tag" do
        post :create, {:link_tag => valid_attributes}, valid_session
        assigns(:link_tag).should be_a(LinkTag)
        assigns(:link_tag).should be_persisted
      end

      it "redirects to the created link_tag" do
        post :create, {:link_tag => valid_attributes}, valid_session
        response.should redirect_to(LinkTag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved link_tag as @link_tag" do
        # Trigger the behavior that occurs when invalid params are submitted
        LinkTag.any_instance.stub(:save).and_return(false)
        post :create, {:link_tag => { "link_id" => "invalid value" }}, valid_session
        assigns(:link_tag).should be_a_new(LinkTag)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LinkTag.any_instance.stub(:save).and_return(false)
        post :create, {:link_tag => { "link_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested link_tag" do
        link_tag = LinkTag.create! valid_attributes
        # Assuming there are no other link_tags in the database, this
        # specifies that the LinkTag created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LinkTag.any_instance.should_receive(:update).with({ "link_id" => "1" })
        put :update, {:id => link_tag.to_param, :link_tag => { "link_id" => "1" }}, valid_session
      end

      it "assigns the requested link_tag as @link_tag" do
        link_tag = LinkTag.create! valid_attributes
        put :update, {:id => link_tag.to_param, :link_tag => valid_attributes}, valid_session
        assigns(:link_tag).should eq(link_tag)
      end

      it "redirects to the link_tag" do
        link_tag = LinkTag.create! valid_attributes
        put :update, {:id => link_tag.to_param, :link_tag => valid_attributes}, valid_session
        response.should redirect_to(link_tag)
      end
    end

    describe "with invalid params" do
      it "assigns the link_tag as @link_tag" do
        link_tag = LinkTag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LinkTag.any_instance.stub(:save).and_return(false)
        put :update, {:id => link_tag.to_param, :link_tag => { "link_id" => "invalid value" }}, valid_session
        assigns(:link_tag).should eq(link_tag)
      end

      it "re-renders the 'edit' template" do
        link_tag = LinkTag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LinkTag.any_instance.stub(:save).and_return(false)
        put :update, {:id => link_tag.to_param, :link_tag => { "link_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested link_tag" do
      link_tag = LinkTag.create! valid_attributes
      expect {
        delete :destroy, {:id => link_tag.to_param}, valid_session
      }.to change(LinkTag, :count).by(-1)
    end

    it "redirects to the link_tags list" do
      link_tag = LinkTag.create! valid_attributes
      delete :destroy, {:id => link_tag.to_param}, valid_session
      response.should redirect_to(link_tags_url)
    end
  end

end
